name: Build on Commit

on:
 - push

jobs:
    mvn:
        uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@1.0.1
        with:
            maven-command: "--batch-mode deploy -Dgpg.skip=true"
            server-id: github
            java-version: 21
            ref: ${{ github.head_ref }}
        secrets:
            maven-token: ${{ secrets.GITHUB_TOKEN }}
