name: Build on Commit

on:
 - push

jobs:
    mvn:
        uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@v1.0.6
        with:
            maven-command: "--batch-mode deploy -Dgpg.skip=true"
            server-id: github
            java-version: 21
            ref: ${{ github.head_ref }}
        secrets:
            maven-token: ${{ secrets.GITHUB_TOKEN }}
